port = 3030

[elastic]
url = "http://localhost:9200"

[ui]
colorscheme = "neon"
[ui.flow.node]
color_attribute = "storage_type"
attributes = ["availability_zone"]
[ui.flow.edge]
attributes = ["storage_type", "availability_zone"]
