/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gDj8jGpjaBq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Progress } from "@/components/ui/progress"
import { useState, useEffect } from "react"
import { ColumnDef } from "@tanstack/react-table"
import { DataTable, wrapSortable } from "./ui/data-table"

import prettyBytes from 'pretty-bytes';
import { gql, useQuery } from "@apollo/client"
import { Badge } from "./ui/badge"
import { parseSize } from "@/lib/utils"

const columns: ColumnDef<any>[] = [
  {
    accessorKey: "name",
    header: wrapSortable.bind(null, "Index"),
  },
  {
    accessorKey: "ip",
    header: wrapSortable.bind(null, "IP"),
  }
];

const GET_NODES = gql`
  query GetNodes {
    nodes {
      nodes {
        name
        ip
      }
    }
  }
`;

export function NodesTable() {
  const { loading, error, data } = useQuery(GET_NODES);

  if (loading) {
    return <Progress />;
  }

  if (error) {
    return <div>Error loading indices</div>;
  }

  return (
    <div className="overflow-auto border rounded-lg">
      <DataTable columns={columns} data={data.nodes.nodes} />
    </div>
  )
}
