// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexInfo = { health: string, status: string, index: string, uuid: string, pri: string, rep: string, "docs.count": string, "docs.deleted": string, "store.size": string, "pri.store.size": string, };
