// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexInfo = { health: string, status: string, index: string, uuid: string, pri: string, rep: string, docs_count: string, docs_deleted: string, store_size: string, pri_store_size: string, };
