// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeInfo = { id: string, host: string, transport_address: string, ip: string, name: string, };
