// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeInfo } from "./NodeInfo";
import type { TranslogInfo } from "./TranslogInfo";
import type { TransportIndexInfo } from "./TransportIndexInfo";
import type { VerifyIndexInfo } from "./VerifyIndexInfo";

export type RecoveryShard = { id: number, shard_type: string, stage: string, primary: boolean, start_time_in_millis: bigint, total_time_in_millis: bigint, source: NodeInfo, target: NodeInfo, index: TransportIndexInfo, translog: TranslogInfo, verify_index: VerifyIndexInfo, };
