// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShallowShard = { index: string, shard: string, prirep: string, state: string, docs: string | null, store: string | null, ip: string, node: string, };
