// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SizeInfo = { total_in_bytes: bigint, reused_in_bytes: bigint, recovered_in_bytes: bigint, recovered_from_snapshot_in_bytes: bigint, percent: string, };
