// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilesInfo } from "./FilesInfo";
import type { SizeInfo } from "./SizeInfo";

export type TransportIndexInfo = { size: SizeInfo, files: FilesInfo, total_time_in_millis: bigint, source_throttle_time_in_millis: bigint, target_throttle_time_in_millis: bigint, };
