// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TranslogInfo = { recovered: number, total: number, percent: string, total_on_start: number, total_time_in_millis: bigint, };
