// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VerifyIndexInfo = { check_index_time_in_millis: bigint, total_time_in_millis: bigint, };
